nestloop optimize  inner 1472
actiontech/dble pull request #3021
Opened 2021-12-21 02:19 UTC by ylinzhu

Reason:  
 Improve 
Type:  
  Improve  
Influences：  
   fix xx

2021-12-21 09:26 UTC, ylinzhu commented
parameters need to be replace

2022-01-06 09:39 UTC, dcy10000 requested changes

2022-01-06 09:39 UTC, dcy10000 commented on src/main/java/com/actiontech/dble/plan/optimizer/MyOptimizer.java
> +                    HintStrategyProcessor.optimize(node, hintPlanInfo);
The naming is inappropriate

2022-01-06 10:07 UTC, dcy10000 requested changes

2022-01-06 10:07 UTC, dcy10000 commented on src/main/java/com/actiontech/dble/plan/optimizer/JoinNestLoopChooser.java
> +        if (leftNode instanceof JoinNode) {
right join maybe JoinNode too.
like  /*!dble:plan=a&b&c*/select * from a right join b on a.id =b.id right join c on b.id=c.id ;

2022-01-10 08:39 UTC, dcy10000 requested changes

2022-01-10 08:39 UTC, dcy10000 commented on src/main/java/com/actiontech/dble/plan/optimizer/JoinNestLoopChooser.java
> +            if (group.getType() == HintPlanNodeGroup.Type.ER) {
this compare doesn't anything about itemFuncEqual?

2022-01-10 08:39 UTC, dcy10000 commented on src/main/java/com/actiontech/dble/plan/optimizer/JoinNestLoopChooser.java
> +                return nodeMap.get(tableName);
always return  NULL ?

2022-01-21 06:20 UTC, dcy10000 approved these changes
lgtm

2022-01-21 06:37 UTC, merged