optimization hint inner 1658
actiontech/dble pull request #3294
Opened 2022-06-29 03:10 UTC by ylinzhu

Reason:  
  Improve 
Type:  
  Improve  
Influences：  
   fix xx

2022-06-30 06:23 UTC, dcy10000 approved these changes

2022-06-30 06:23 UTC, dcy10000 commented on src/main/java/com/actiontech/dble/plan/optimizer/HintPlanInfo.java
> +    private HashMap<String, HintPlanParse.Type> hintPlanNodeMap = Maps.newHashMap();
must use linkedmap

2022-06-30 06:52 UTC, dcy10000 requested changes

2022-06-30 06:52 UTC, dcy10000 commented on src/main/java/com/actiontech/dble/plan/optimizer/HintPlanInfo.java
> +    private HashMap<String, HintPlanParse.Type> hintPlanNodeMap = Maps.newHashMap();
must use linkedmap

2022-07-01 06:20 UTC, dcy10000 commented
d|(a&b)&c can't parsed

2022-07-12 07:01 UTC, PanternBao approved these changes
lgtm

2022-07-12 07:06 UTC, dcy10000 approved these changes
lgtm

2022-07-12 07:58 UTC, merged