[inner-1855] fix: in 'join on subquery', subquery is executed repeatedly
actiontech/dble pull request #3358
Opened 2022-08-15 09:04 UTC by wenyh1

Reason:  
  BUG inner 1855
Type:  
  BUG/Improve  
Influences：  
   fix xx

2022-08-18 09:56 UTC, ylinzhu requested changes

2022-08-19 03:09 UTC, wenyh1 commented on src/main/java/com/actiontech/dble/plan/visitor/MySQLPlanNodeVisitor.java
> +                joinNode.setOtherJoinOnFilter(FilterUtils.and(orgOtherJoin, filter));
ok

2022-08-19 03:23 UTC, ylinzhu approved these changes
ok

2022-08-19 03:24 UTC, ylinzhu requested changes
ci is not running properly. Wait for ci to pass

2022-08-19 05:29 UTC, ylinzhu approved these changes

2022-08-19 05:29 UTC, merged