add delay detection inner 1846
actiontech/dble pull request #3428
Opened 2022-10-09 05:22 UTC by ylinzhu

Reason:  
   Improve 
Type:  
        Improve  
Influences：  
   fix xx

2022-10-21 03:34 UTC, dcy10000 requested changes

2022-10-21 03:34 UTC, dcy10000 commented on src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
> +            isNotDelay = status == DelayDetectionStatus.ERROR || status == DelayDetectionStatus.TIMEOUT;
opposite？

2022-10-21 07:52 UTC, ylinzhu commented on src/main/java/com/actiontech/dble/backend/datasource/PhysicalDbInstance.java
> +            isNotDelay = status == DelayDetectionStatus.ERROR || status == DelayDetectionStatus.TIMEOUT;
ok

2022-10-24 02:17 UTC, dcy10000 requested changes

2022-10-24 02:17 UTC, dcy10000 commented on src/main/java/com/actiontech/dble/backend/delyDetection/DelayDetection.java
> +    private String crateTabletSQL;
Table?

2022-10-24 05:02 UTC, dcy10000 approved these changes
ok

2022-10-24 05:17 UTC, merged