add tcp level parameters to control connections inner 1716
actiontech/dble pull request #3649
Opened 2023-04-03 02:51 UTC by ylinzhu

Reason:  
  Improve 
Type:  
  Improve  
Influences：  
   fix xx

2023-04-03 03:33 UTC, ylinzhu commented
wait update jdbk version

2023-04-12 06:34 UTC, dcy10000 requested changes

2023-04-12 06:34 UTC, dcy10000 commented on src/main/java/com/actiontech/dble/net/DbleSocketOptions.java
> +    public static void defaultKeepAliveOptions(NetworkChannel channel) throws IOException {
maybe "setKeepAliveOptions" is better

2023-04-17 02:22 UTC, dcy10000 approved these changes
lgtm

2023-04-17 09:44 UTC, merged