[inner-2218] Configuration support for HTAP
actiontech/dble pull request #3731
Opened 2023-06-09 09:05 UTC by wenyh1

Reason:  
  BUG #. or Improve #.  
Type:  
  BUG/Improve  
Influences：  
   fix xx

2023-06-28 09:12 UTC, LUAgam requested changes

2023-06-28 09:25 UTC, wenyh1 commented on src/main/java/com/actiontech/dble/services/manager/response/ChangeItemType.java
> +    PHYSICAL_DB_GROUP(), PHYSICAL_DB_INSTANCE(), SHARDING_NODE(), AP_NODE(), USERNAME();
get

2023-06-28 09:26 UTC, wenyh1 commented on src/main/java/com/actiontech/dble/config/converter/ShardingConverter.java
> +                errorInfos.add(new ErrorInfo("Xml", "WARNING", "shardingNode " + apNodeName + " is useless"));
get

2023-06-29 02:08 UTC, LUAgam approved these changes
lgtm

2023-06-29 03:22 UTC, merged